/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlternativenRouteImport } from './routes/alternativen'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as GewerbeRouteImport } from './routes/gewerbe'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as KommuneRouteImport } from './routes/kommune'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as LeistungenRouteImport } from './routes/leistungen'
import { Route as NachweiseRouteImport } from './routes/nachweise'
import { Route as NaturgaertenRouteImport } from './routes/naturgaerten'
import { Route as NeubuergerRouteImport } from './routes/neubuerger'
import { Route as PflanzenRouteImport } from './routes/pflanzen'
import { Route as PlanerRouteImport } from './routes/planer'
import { Route as PrivatRouteImport } from './routes/privat'
import { Route as ProjekteRouteImport } from './routes/projekte'
import { Route as UeberRouteImport } from './routes/ueber'
import { Route as PflanzenSlugRouteImport } from './routes/pflanzen.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlternativenRoute = AlternativenRouteImport.update({
  id: '/alternativen',
  path: '/alternativen',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const GewerbeRoute = GewerbeRouteImport.update({
  id: '/gewerbe',
  path: '/gewerbe',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const KommuneRoute = KommuneRouteImport.update({
  id: '/kommune',
  path: '/kommune',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenRoute = LeistungenRouteImport.update({
  id: '/leistungen',
  path: '/leistungen',
  getParentRoute: () => rootRouteImport,
} as any)
const NachweiseRoute = NachweiseRouteImport.update({
  id: '/nachweise',
  path: '/nachweise',
  getParentRoute: () => rootRouteImport,
} as any)
const NaturgaertenRoute = NaturgaertenRouteImport.update({
  id: '/naturgaerten',
  path: '/naturgaerten',
  getParentRoute: () => rootRouteImport,
} as any)
const NeubuergerRoute = NeubuergerRouteImport.update({
  id: '/neubuerger',
  path: '/neubuerger',
  getParentRoute: () => rootRouteImport,
} as any)
const PflanzenRoute = PflanzenRouteImport.update({
  id: '/pflanzen',
  path: '/pflanzen',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanerRoute = PlanerRouteImport.update({
  id: '/planer',
  path: '/planer',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivatRoute = PrivatRouteImport.update({
  id: '/privat',
  path: '/privat',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjekteRoute = ProjekteRouteImport.update({
  id: '/projekte',
  path: '/projekte',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberRoute = UeberRouteImport.update({
  id: '/ueber',
  path: '/ueber',
  getParentRoute: () => rootRouteImport,
} as any)
const PflanzenSlugRoute = PflanzenSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PflanzenRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alternativen': typeof AlternativenRoute
  '/datenschutz': typeof DatenschutzRoute
  '/gewerbe': typeof GewerbeRoute
  '/impressum': typeof ImpressumRoute
  '/kommune': typeof KommuneRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/nachweise': typeof NachweiseRoute
  '/naturgaerten': typeof NaturgaertenRoute
  '/neubuerger': typeof NeubuergerRoute
  '/pflanzen': typeof PflanzenRouteWithChildren
  '/planer': typeof PlanerRoute
  '/privat': typeof PrivatRoute
  '/projekte': typeof ProjekteRoute
  '/ueber': typeof UeberRoute
  '/pflanzen/$slug': typeof PflanzenSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alternativen': typeof AlternativenRoute
  '/datenschutz': typeof DatenschutzRoute
  '/gewerbe': typeof GewerbeRoute
  '/impressum': typeof ImpressumRoute
  '/kommune': typeof KommuneRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/nachweise': typeof NachweiseRoute
  '/naturgaerten': typeof NaturgaertenRoute
  '/neubuerger': typeof NeubuergerRoute
  '/pflanzen': typeof PflanzenRouteWithChildren
  '/planer': typeof PlanerRoute
  '/privat': typeof PrivatRoute
  '/projekte': typeof ProjekteRoute
  '/ueber': typeof UeberRoute
  '/pflanzen/$slug': typeof PflanzenSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alternativen': typeof AlternativenRoute
  '/datenschutz': typeof DatenschutzRoute
  '/gewerbe': typeof GewerbeRoute
  '/impressum': typeof ImpressumRoute
  '/kommune': typeof KommuneRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRoute
  '/nachweise': typeof NachweiseRoute
  '/naturgaerten': typeof NaturgaertenRoute
  '/neubuerger': typeof NeubuergerRoute
  '/pflanzen': typeof PflanzenRouteWithChildren
  '/planer': typeof PlanerRoute
  '/privat': typeof PrivatRoute
  '/projekte': typeof ProjekteRoute
  '/ueber': typeof UeberRoute
  '/pflanzen/$slug': typeof PflanzenSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alternativen'
    | '/datenschutz'
    | '/gewerbe'
    | '/impressum'
    | '/kommune'
    | '/kontakt'
    | '/leistungen'
    | '/nachweise'
    | '/naturgaerten'
    | '/neubuerger'
    | '/pflanzen'
    | '/planer'
    | '/privat'
    | '/projekte'
    | '/ueber'
    | '/pflanzen/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alternativen'
    | '/datenschutz'
    | '/gewerbe'
    | '/impressum'
    | '/kommune'
    | '/kontakt'
    | '/leistungen'
    | '/nachweise'
    | '/naturgaerten'
    | '/neubuerger'
    | '/pflanzen'
    | '/planer'
    | '/privat'
    | '/projekte'
    | '/ueber'
    | '/pflanzen/$slug'
  id:
    | '__root__'
    | '/'
    | '/alternativen'
    | '/datenschutz'
    | '/gewerbe'
    | '/impressum'
    | '/kommune'
    | '/kontakt'
    | '/leistungen'
    | '/nachweise'
    | '/naturgaerten'
    | '/neubuerger'
    | '/pflanzen'
    | '/planer'
    | '/privat'
    | '/projekte'
    | '/ueber'
    | '/pflanzen/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlternativenRoute: typeof AlternativenRoute
  DatenschutzRoute: typeof DatenschutzRoute
  GewerbeRoute: typeof GewerbeRoute
  ImpressumRoute: typeof ImpressumRoute
  KommuneRoute: typeof KommuneRoute
  KontaktRoute: typeof KontaktRoute
  LeistungenRoute: typeof LeistungenRoute
  NachweiseRoute: typeof NachweiseRoute
  NaturgaertenRoute: typeof NaturgaertenRoute
  NeubuergerRoute: typeof NeubuergerRoute
  PflanzenRoute: typeof PflanzenRouteWithChildren
  PlanerRoute: typeof PlanerRoute
  PrivatRoute: typeof PrivatRoute
  ProjekteRoute: typeof ProjekteRoute
  UeberRoute: typeof UeberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alternativen': {
      id: '/alternativen'
      path: '/alternativen'
      fullPath: '/alternativen'
      preLoaderRoute: typeof AlternativenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gewerbe': {
      id: '/gewerbe'
      path: '/gewerbe'
      fullPath: '/gewerbe'
      preLoaderRoute: typeof GewerbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kommune': {
      id: '/kommune'
      path: '/kommune'
      fullPath: '/kommune'
      preLoaderRoute: typeof KommuneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen': {
      id: '/leistungen'
      path: '/leistungen'
      fullPath: '/leistungen'
      preLoaderRoute: typeof LeistungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nachweise': {
      id: '/nachweise'
      path: '/nachweise'
      fullPath: '/nachweise'
      preLoaderRoute: typeof NachweiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/naturgaerten': {
      id: '/naturgaerten'
      path: '/naturgaerten'
      fullPath: '/naturgaerten'
      preLoaderRoute: typeof NaturgaertenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neubuerger': {
      id: '/neubuerger'
      path: '/neubuerger'
      fullPath: '/neubuerger'
      preLoaderRoute: typeof NeubuergerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pflanzen': {
      id: '/pflanzen'
      path: '/pflanzen'
      fullPath: '/pflanzen'
      preLoaderRoute: typeof PflanzenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planer': {
      id: '/planer'
      path: '/planer'
      fullPath: '/planer'
      preLoaderRoute: typeof PlanerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privat': {
      id: '/privat'
      path: '/privat'
      fullPath: '/privat'
      preLoaderRoute: typeof PrivatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekte': {
      id: '/projekte'
      path: '/projekte'
      fullPath: '/projekte'
      preLoaderRoute: typeof ProjekteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueber': {
      id: '/ueber'
      path: '/ueber'
      fullPath: '/ueber'
      preLoaderRoute: typeof UeberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pflanzen/$slug': {
      id: '/pflanzen/$slug'
      path: '/$slug'
      fullPath: '/pflanzen/$slug'
      preLoaderRoute: typeof PflanzenSlugRouteImport
      parentRoute: typeof PflanzenRoute
    }
  }
}

interface PflanzenRouteChildren {
  PflanzenSlugRoute: typeof PflanzenSlugRoute
}

const PflanzenRouteChildren: PflanzenRouteChildren = {
  PflanzenSlugRoute: PflanzenSlugRoute,
}

const PflanzenRouteWithChildren = PflanzenRoute._addFileChildren(
  PflanzenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlternativenRoute: AlternativenRoute,
  DatenschutzRoute: DatenschutzRoute,
  GewerbeRoute: GewerbeRoute,
  ImpressumRoute: ImpressumRoute,
  KommuneRoute: KommuneRoute,
  KontaktRoute: KontaktRoute,
  LeistungenRoute: LeistungenRoute,
  NachweiseRoute: NachweiseRoute,
  NaturgaertenRoute: NaturgaertenRoute,
  NeubuergerRoute: NeubuergerRoute,
  PflanzenRoute: PflanzenRouteWithChildren,
  PlanerRoute: PlanerRoute,
  PrivatRoute: PrivatRoute,
  ProjekteRoute: ProjekteRoute,
  UeberRoute: UeberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
